FROM redis:6.2.4
MAINTAINER running "A576236148946@126.com"

# 安装相关系统必备依赖
RUN apt update \
    && apt install procps -y \
    && apt install net-tools -y \
    && apt install vim -y \
    && apt install curl -y

COPY redis_6.2.4/redis.conf /usr/local/etc/redis/redis.conf

WORKDIR /myself
VOLUME ["/myself"]

CMD ["redis-server" , "/usr/local/etc/redis/redis.conf"]